### ISSUE TITLE
Using Pitch or Stretch bugs out the audio

### ISSUE THREAD

**Issue by secretkiillerofnames** [polyeffects/digit_ui#11]
Rate works fine.
If pitch or stretch is changed even slightly the audio starts glitching.
It doesn't change when returning pitch to 0 or stretch to 1.
It remains glitchy until new audio is recorded over the buffer.
Overdubbing doesn't change the glitching.
DSP shows as 65% on my patch (attached).
Slight glitching seems to be evident when multiplying loops also.
[Passthrutemp.zip](https://github.com/polyeffects/digit_ui/files/6262790/Passthrutemp.zip)

**Comment by phenoplastic** [comment]
Yes, noticed this also.

**Comment by loki42** [comment]
pitch shifting and time stretch is using a ton of CPU. Also I think the bug here is incorrect CPU usage reporting when using the loopler.
