### ISSUE TITLE
Receiving midi on all channels (3.1)

### ISSUE THREAD

**Issue by Andy-watt125** [polyeffects/digit_ui#12]
When tapping the midi learn function next to a parameter inside a module, Beebo is responding to a midi message sent out on any channel, regardless of what channel Beebo is actually set to. 

The midi CC module does work as intended, and only responds to CC #s and values sent on the assigned midi channel.

**Comment by scofieldloves** [comment]
IMO, I think that is the way it should must work. Learn (receive) from all channels to easy select whatever and wherever midi controller i wanna use. For example... A novation circuit have 8 macro pots for each midi channel, but actually (virtually) have more than 50 using other functions like fx and mixer. Limiting that to a pre selected channel would be a bad idea for those who have more than one midi controller and/or a midi controller with various independent midi channels.

**Comment by Andy-watt125** [comment]
In your examples, setting Beebo to receive midi on all channels would still let you do all of that.

I have 4 other midi devices on my board, if I set Beebo to a particular midi channel, the expectation would be that it only listens for midi information on that channel. Currently I can assign a CC# to a parameter on Beebo’s midi channel, but then Beebo responds to that CC# sent out on any midi channel. That’s not exactly ideal in a more complex setup

**Comment by scofieldloves** [comment]
I say what you say too.... 
Recive on all channels. 

So, what is the problem or bug if now it is doing that? 
Midi to cc module is other history, as is intended to precisely give a command to a specific parameter. So, it now do what it should do. 
I don't see any bug. 
Where i see a bug it is on cc to midi, if beebo is intended to act as external controller, but i already open a issue last week about that. 

Btw, i have 7 midi controllers and another 8 midi effects. Upss... Only 16 midi channels should be considered a bug too.

**Comment by loki42** [comment]
Fixed in next update. Can MIDI learn on all channels but only responds to the message and channel that was learned. Previously would respond in omni mode.
