### ISSUE TITLE
Screen freeze (3.2 beta 2)

### ISSUE THREAD

**Issue by HelveticaARH** [polyeffects/digit_ui#13]
I was messing with the synth modules yesterday without the looper. After some time (probably 15 - 30 minutes in), the screen froze on the Granular module parameters. There's output sound but I can not tweak the parameters of the Granular module nor get back to the home screen (the icon does not appear); moreover, the left-most icons show the connect/disconnect icon and nothing else.

**Comment by loki42** [comment]
fixed screen getting stuck if preset changed while in looper or granular. Might have fixed this. Reopen if you can reproduce it with 3.4
