### ISSUE TITLE
Bypass vs Straight through volume increase

### ISSUE THREAD

**Issue by pcrlcc** [polyeffects/digit_ui#15]
When I simply connect the Input to the Output without any effects I notice a slight increase in volume when digit is activated vs. when it is in bypass mode.

**Comment by loki42** [comment]
in settings set input gain to a lower value (-4 for example) then press set input level. Then check level vs bypass.

**Comment by pcrlcc** [comment]
Cool, thanks. Do you need the button at all then? Why not set the level on each change? Would make the UI leaner or are there other issues that prevent this?

Another way would be to make the button inactive when you open the settings and only make it active once the user made a change. That would make a bit clearer I think. 

When I saw the button I though this is some auto-input level set button : )
