### ISSUE TITLE
When a saved preset with two loopers is loaded, a third looper in module is added on load

### ISSUE THREAD

**Issue by pcrlcc** [polyeffects/digit_ui#21]

**Comment by loki42** [comment]
think i fixed this in e877f7e if it's to do with how many loops are added.  Otherwise if it's number of actual module on the main screen I can't reproduce it.

**Comment by pcrlcc** [comment]
Here's an example patch where it's happening. Once you load the patch a third looper ist added. When I remove the looper and save the patch, a third looper is added again after boot/load of the patch.

[Picco.instr.zip](https://github.com/polyeffects/digit_ui/files/6489096/Picco.instr.zip)
