### ISSUE TITLE
MIDI Sync issues - LFO running out of sync

### ISSUE THREAD

**Issue by michaelwedenig** [polyeffects/digit_ui#39]
Hey everyone, 

I'm running into some sync issues here. 

- Using my **Digitone** as master clock. My signal chain on Hector is **MIDI clock in** - > **LFO** - > **Euclidean**. After short time Euclidian starts to fall behind.
I also tried triggering Oscillators directly with the LFO but it's the same thing. If I change the LFO's **Tempo Multiplier** to 1.001 it's better but still a bit too slow. At 1.002 it's already too fast.
**Drum Patterns** accepts MIDI clock directly and seems to work fine - so the problem must lie with the LFO. 

- (Idk if this issue can be addressed from the Hector-side) Using **Polyend Tracker** as master clock. Everytime playback starts on the Tracker, Hector needs around 11 seconds to catch up. The problem here seems to be, that the Tracker (unlike Digitone) doesn't send out a clock signal when stopped/paused.

**Comment by loki42** [comment]
fixed in update to MIDI clock in module,  polyeffects/PolyMclkIn.lv2@64acb88d6c574b4efc743b770d1d22444391ba02
