### ISSUE TITLE
Git build issue

### ISSUE THREAD

**Issue by prokoudine** [polyeffects/digit_ui#40]
```
$ qmake digit.pro 
Info: creating stash file /home/alex/soft/sound/polyeffects/digit_ui/.qmake.stash
/home/alex/soft/sound/polyeffects/digit_ui/icons/icons.qrc: Warning: potential duplicate alias detected: 'connect.svg'
WARNING: Failure to find: /home/alex/soft/sound/polyeffects/digit_ui/qml/ionicons.js
icons/icons.qrc: Warning: potential duplicate alias detected: 'connect.svg'
```

which eventually leads to...

`make: *** No rule to make target 'qml/ionicons.js', needed by 'qml_ionicons_js.cpp'.  Stop.`

**Comment by loki42** [comment]
Removed these files, the front end is python based (pyside2) so nothing to compile with qmake. I'd accidentally added some of my early test files and not removed them.
