### ISSUE TITLE
In & Out's dedicated levels and a mixer 

### ISSUE THREAD

**Issue by scofieldloves** [polyeffects/digit_ui#5]
No bug, but could it be possible to have, on each of the 4 in and out, a control for level and maybe for clipping?
I found that many presets i have made with different routing options, and depending on the type of effects, it results on very loud levels and makes some clipping. 
VCA's seems not to be the best solution. 

By the way, a dedicated mixer with at least 4 inputs, would be great and very useful.

**Comment by loki42** [comment]
mixer module has been added, wet dry also added.
